# Generated by Django 4.2.10 on 2024-02-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
