# Generated by Django 4.2.10 on 2024-02-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='profilecomment',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='profilecomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='profilecomment',
            name='body',
        ),
        migrations.RemoveField(
            model_name='profilecomment',
            name='created_on',
        ),
    ]
