# Generated by Django 4.2.10 on 2024-03-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        ('user_profile', '0002_socials_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='socials',
            name='fav_pokemon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fav_pokemon', to='database.pokedatabase'),
        ),
    ]
