# Generated by Django 4.2.10 on 2024-02-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profilecomment_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileComment',
            new_name='UserProfile',
        ),
    ]
