# Generated by Django 4.2.10 on 2024-03-18 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        ('user_profile', '0003_socials_fav_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socials',
            name='fav_pokemon',
            field=models.ForeignKey(default='placeholder', on_delete=django.db.models.deletion.CASCADE, related_name='fav_pokemon', to='database.pokedatabase'),
        ),
    ]
